class Movies {
  final int id, release, numOfRatings, criticsReview, metascoreRating;
  final String title, poster, backdrop, overview, rating, runtime;
  final List<String> genre;

  Movies(
      {this.id,
      this.title,
      this.poster,
      this.backdrop,
      this.overview,
      this.rating,
      this.release,
      this.runtime,
      this.criticsReview,
      this.metascoreRating,
      this.numOfRatings,
      this.genre});
}

List<Movies> movies = [
  Movies(
    id: 1,
    title: 'Godzilla vs. Kong',
    poster: 'assets/images/pKong.jpg',
    backdrop:
        'assets/images/bKong.jpg',
    overview:
        'In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.',
    rating: '8.3',
    criticsReview: 224,
    metascoreRating: 80,
    numOfRatings: 12644,
    runtime: "127 Minutes",
    genre: ["Action", "War", "Sci-Fi"],
    release: 2021,
  ),
  Movies(
    id: 2,
    title: 'Thunder Force',
    poster: 'assets/images/pForce.jpg',
    backdrop: 'assets/images/bForce.jpg',
    overview:
        'In a world where supervillains are commonplace, two estranged childhood best friends reunite after one devises a treatment that gives them powers to protect their city.',
    rating: '5.8',
    criticsReview: 92,
    metascoreRating: 66,
    numOfRatings: 23453,
    runtime: "89 Minutes",
    genre: ["Action", "Drama", "Comedy"],
    release: 2021,
  ),
  Movies(
    id: 3,
    title: 'Mortal Kombat',
    poster: 'assets/images/pMk.jpg',
    backdrop: 'assets/images/bMk.jpg',
    overview:
        'Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung\'s best warrior, Sub-Zero, seeks out and trains with Earth\'s greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.',
    rating: '8.2',
    criticsReview: 129,
    metascoreRating: 78,
    numOfRatings: 12654,
    runtime: "98 Minutes",
    genre: ["Action", "Fight"],
    release: 2021,
  ),
  Movies(
    id: 4,
    title: 'Zack Snyder\'s Justice League',
    poster: 'assets/images/pJustice.jpg',
    backdrop: 'assets/images/bJustice.jpg',
    overview:
        'Determined to ensure Superman\'s ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.',
    rating: '8.5',
    criticsReview: 526,
    metascoreRating: 90,
    numOfRatings: 23464,
    runtime: "238 Minutes",
    genre: ["Action", "Adventure"],
    release: 2021,
  ),
  Movies(
    id: 5,
    title: 'The Marksman',
    poster: 'assets/images/pMarksman.jpg',
    backdrop: 'assets/images/bJustice.jpg',
    overview:
        'Jim Hanson’s quiet life is suddenly disturbed by two people crossing the US/Mexico border – a woman and her young son – desperate to flee a Mexican cartel. After a shootout leaves the mother dead, Jim becomes the boy’s reluctant defender. He embraces his role as Miguel’s protector and will stop at nothing to get him to safety, as they go on the run from the relentless assassins.',
    rating: '7.1',
    criticsReview: 87,
    metascoreRating: 76,
    numOfRatings: 3643,
    runtime: "109 Minutes",
    genre: ["Action", "Crime"],
    release: 2021,
  ),
  Movies(
    id: 6,
    title: 'Chaos Walking',
    poster: 'assets/images/pChaosWalking.jpg',
    backdrop: 'assets/images/bChaosWalking.jpg',
    overview:
        'Two unlikely companions embark on a perilous adventure through the badlands of an unexplored planet as they try to escape a dangerous and disorienting reality, where all inner thoughts are seen and heard by everyone.',
    rating: '7.4',
    criticsReview: 120,
    metascoreRating: 75,
    numOfRatings: 9340,
    runtime: "93 Minutes",
    genre: ["Action", "Drama", "Thriller"],
    release: 2021,
  ),
  Movies(
    id: 7,
    title: 'Nobody',
    poster: 'assets/images/pNobody.jpg',
    backdrop: 'assets/images/bNobody.jpg',
    overview:
        'Hutch Mansell, a suburban dad, overlooked husband, nothing neighbor — a \"nobody.\" When two thieves break into his home one night, Hutch\'s unknown long-simmering rage is ignited and propels him on a brutal path that will uncover dark secrets he fought to leave behind.',
    rating: '8.5',
    criticsReview: 235,
    metascoreRating: 72,
    numOfRatings: 12646,
    runtime: "111 Minutes",
    genre: ["Action", "Thriller"],
    release: 2021,
  ),
  Movies(
    id: 8,
    title: 'Raya and the Last Dragon',
    poster: 'assets/images/pRaya.jpg',
    backdrop: 'assets/images/bRaya.jpg',
    overview:
        'Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. But when an evil force threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, that same evil has returned and it’s up to a lone warrior, Raya, to track down the legendary last dragon to restore the fractured land and its divided people.',
    rating: '8.3',
    criticsReview: 112,
    metascoreRating: 80,
    numOfRatings: 2154,
    runtime: "115 Minutes",
    genre: ["Adventure", "Animation"],
    release: 2021,
  ),
  Movies(
    id: 9,
    title: 'MK : Scorpion\'s Revenge',
    poster: 'assets/images/pMkScorpio.jpg',
    backdrop: 'assets/images/bMkScorpio.jpg',
    overview:
        'After the vicious slaughter of his family by stone-cold mercenary Sub-Zero, Hanzo Hasashi is exiled to the torturous Netherrealm. There, in exchange for his servitude to the sinister Quan Chi, he’s given a chance to avenge his family – and is resurrected as Scorpion, a lost soul bent on revenge. Back on Earthrealm, Lord Raiden gathers a team of elite warriors – Shaolin monk Liu Kang, Special Forces officer Sonya Blade and action star Johnny Cage – an unlikely band of heroes with one chance to save humanity. To do this, they must defeat Shang Tsung’s horde of Outworld gladiators and reign over the Mortal Kombat tournament.',
    rating: '8.4',
    criticsReview: 176,
    metascoreRating: 82,
    numOfRatings: 1290,
    runtime: "87 Minutes",
    genre: ["Action", "Adventure"],
    release: 2020,
  ),
  Movies(
    id: 10,
    title: 'The Unholy',
    poster: 'assets/images/pUnholy.jpg',
    backdrop: 'assets/images/bUnholy.jpg',
    overview:
        'Alice, a young hearing-impaired girl who, after a supposed visitation from the Virgin Mary, is inexplicably able to hear, speak and heal the sick. As word spreads and people from near and far flock to witness her miracles, a disgraced journalist hoping to revive his career visits the small New England town to investigate. When terrifying events begin to happen all around, he starts to question if these phenomena are the works of the Virgin Mary or something much more sinister.',
    rating: '5.5',
    criticsReview: 129,
    metascoreRating: 69,
    numOfRatings: 9273,
    runtime: "98 Minutes",
    genre: ["Horror", "Thriller"],
    release: 2021,
  ),
];
